version: '3.7'

services:
  app:
    image: hadyanadam/go-gin-gorm-learn
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    expose:
      - 5432
    volumes:
      - golang_api_vol:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=golang_api

volumes:
  golang_api_vol: