version: '3.7'

services:
#   app:
#     build: ./app
#     command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
#     ports:
#       - 8000:8000
#     env_file:
#       - ./app/src/.env.dev
#     depends_on:
#       - db

  db:
    image: postgres:12.0-alpine
    ports:
      - 5433:5432
    volumes:
      - golang_api_vol:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=golang_api

volumes:
  golang_api_vol: